Add getText(), postForText() functions
Functions for requests to endpoint that return text/plain; we just call
it “text” because most of this “plain text” is really wikitext. (Also,
this way, the response formats “JSON”, “text” and “HTML” are all one
word (ish) each, which is nice.)

For the return type, we use boxed String instances, so that the returned
values have an identity and can be used as input for getResponseStatus()
(and potential future functions like getResponseHeaders() or
getResponseContentType()). The alternative would be returning objects
like { text: 'body text' } (or { html: '<p>HTML</p>' } for the HTML
functions), and I went back and forth between these options in my mind,
but eventually settled on the boxed String for now; see also [1]. If it
causes issues, we can change it to the object form.

In the unit tests, a new assertion .box() is used to both simplify the
tests and produce nicer failure messages; I want to see

    AssertionError: expected 'wrong text' to equal 'right text'
    + expected - actual

    -wrong text
    +right text

rather than

    AssertionError: expected 'wrong text' to deeply equal 'right text'
    + expected - actual

     {
    -  "0": "w"
    -  "1": "r"
    -  "2": "o"
    -  "3": "n"
    -  "4": "g"
    +  "0": "r"
    +  "1": "i"
    +  "2": "g"
    +  "3": "h"
    +  "4": "t"
       "5": " "
       "6": "t"
       "7": "e"
       "8": "x"

Note that we can’t integration-test getText(), because endpoints that
return text are quite scarce and none of them take GET requests:

    curl -sL https://en.wikipedia.org/w/rest.php/specs/v0/module/- |
        jq '
            .paths |
            to_entries |
            .[] |
            select(
                .value |
                .[] |
                .responses |
                .[] |
                .content.["text/plain"]
            ) |
            { path: .key, methods: .value | keys }
        '

[1]: https://wikis.world/@LucasWerkmeister/116256279320124252